server:
  port: 8080
  servlet:
    session:
      cookie:
        name: JESSIONID
spring:
#  security:
#    user:
#      name: admin
#      password: admin
  h2:
    console:
        enabled: true
        path: /h2-console
        settings:
          web-allow-others: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/app;DB_CLOSE_DELAY=-1
    name:
    username: app
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
    hibernate:
      ddl-auto: update



#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://127.0.0.1/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
#    name:
#    username: root
#    password:
##    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#        data-source-properties:
#            cachePrepStmts: true
#            prepStmtCacheSize: 250
#            prepStmtCacheSqlLimit: 2048
#            useServerPrepStmts: true
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
#    database: MYSQL
#    show-sql: true
#    properties:
#        hibernate.id.new_generator_mappings: true
#        hibernate.connection.provider_disables_autocommit: true
#        hibernate.cache.use_second_level_cache: false
#        hibernate.cache.use_query_cache: false
#        hibernate.generate_statistics: true
#    hibernate:
#      ddl-auto: update
  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
